---
name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: ru-central1
  YC_API_ENDPOINT: https://api.cloud.yandex.net
  TF_STATE_KEY: main-infrastructure/terraform.tfstate
  TF_VERSION: "1.7.0"

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          cat <<EOF > $HOME/.aws/credentials
          [default]
          aws_access_key_id=${{ secrets.YC_S3_ACCESS_KEY }}
          aws_secret_access_key=${{ secrets.YC_S3_SECRET_KEY }}
          EOF
          cat <<EOF > $HOME/.aws/config
          [default]
          region=${{ env.AWS_REGION }}
          endpoint_url=https://storage.yandexcloud.net
          EOF

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.YC_S3_BUCKET_NAME }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="endpoint=https://storage.yandexcloud.net" \
            -backend-config="skip_region_validation=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="yc_token=${{ secrets.YC_OAUTH }}" \
            -var="cloud_id=${{ secrets.TF_VAR_CLOUD_ID }}" \
            -var="folder_id=${{ secrets.TF_VAR_FOLDER_ID }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="service_account_id=${{ secrets.SERVICE_ACCOUNT_ID }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="yc_token=${{ secrets.YC_OAUTH }}" \
            -var="cloud_id=${{ secrets.TF_VAR_CLOUD_ID }}" \
            -var="folder_id=${{ secrets.TF_VAR_FOLDER_ID }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="service_account_id=${{ secrets.SERVICE_ACCOUNT_ID }}"
