---
name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ru-central1
  TF_STATE_KEY: main-infrastructure/terraform.tfstate
  TF_VERSION: "1.7.0"

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          echo "[default]" > $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.YC_S3_ACCESS_KEY }}" \
            >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.YC_S3_SECRET_KEY }}" \
            >> $HOME/.aws/credentials
          echo "[default]" > $HOME/.aws/config
          echo "region=${{ env.AWS_REGION }}" >> $HOME/.aws/config
          echo "endpoint_url=https://storage.yandexcloud.net" \
            >> $HOME/.aws/config

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.YC_S3_BUCKET_NAME }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="endpoint=https://storage.yandexcloud.net" \
            -backend-config="skip_region_validation=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
