name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    container:
      image: cr.yandex/yc/yandex-cloud-cli:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS CLI for Yandex Cloud S3
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.YC_S3_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.YC_S3_SECRET_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=ru-central1" >> ~/.aws/config
          echo "endpoint_url=https://storage.yandexcloud.net" >> ~/.aws/config

      - name: Configure YC CLI
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_cloud_id }}
          TF_VAR_folder_id: ${{ secrets.TF_VAR_folder_id }}
        run: |
          echo "$YC_SERVICE_ACCOUNT_KEY" > key.json
          yc config set service-account-key key.json
          yc config set cloud-id $TF_VAR_cloud_id
          yc config set folder-id $TF_VAR_folder_id
          yc config list

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.YC_S3_BUCKET_NAME }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
